### ISSUE TITLE
Precompiled files do not work with linux

### ISSUE THREAD

**Issue by styler00dollar** [nihui/cain-ncnn-vulkan#1]
It is not possible to run the precompiled files in linux. Even a simple help output does not seem to work and the error message seems always the same. I tested all linux builds from "pytorch" in Google Colab and I got this output. The same error appears in "it actually works sometimes".
```
!./cain-ncnn-vulkan -h

./cain-ncnn-vulkan: error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory
```

**Comment by nihui** [comment]
apt-get install libvulkan

**Comment by styler00dollar** [comment]
```
!apt-get install libvulkan
E: Unable to locate package libvulkan
```
But ```!sudo apt-get install -y libvulkan-dev``` works. Thank you. You may want to add this information to the readme. I thought this is only required when it is built from source.

Small sidenote: You should probably place ```cain-ncnn-vulkan```,  ```cain.bin``` and ```cain.param``` in the same zip level or make a small fix, since that code works if all files are in the same folder. The output is a gray interpolated image by default. Currently  ```cain.bin``` and ```cain.param``` are inside ```/cain``` and creates this error.
```
[0 Tesla P100-PCIE-16GB]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 Tesla P100-PCIE-16GB]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 Tesla P100-PCIE-16GB]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
fopen cain.param failed
fopen cain.bin failed
find_blob_index_by_name x.1 failed
find_blob_index_by_name x.3 failed
find_blob_index_by_name 4070 failed
...
```
