### ISSUE TITLE
Interpolated frames are grey

### ISSUE THREAD

**Issue by herrartist** [nihui/cain-ncnn-vulkan#11]
The interpolated png frames are just gray (Mac and Windows the same). I get this error: fopen cain.param failed
fopen cain.bin failed
decode image input_frames/.DS_Store failed
decode image input_frames/.DS_Store failed
find_blob_index_by_name x.1 failed
find_blob_index_by_name x.3 failed
find_blob_index_by_name 4070 failed
find_blob_index_by_name x.1 failed
find_blob_index_by_name x.3 failed
find_blob_index_by_name 4070 failed
and so on.

**Comment by natowi** [comment]
Try creating a new input (input_frames) and output (output_frames) folder in the same directory as cain. Then run `cain-ncnn-vulkan -i input_frames -o output_frames`

**Comment by n00mkrad** [comment]
Also make sure to move the model files into the same folder as the executable.

**Comment by herrartist** [comment]
Thank you for your kind support! It works now. But I am interested how to (with FFMPEG-commands) to up convert a video with 6 fps to 24 fps. This is for creating in-betweens for an animation movie.

**Comment by natowi** [comment]
FFMPEG is just used to extract the frames as described here https://github.com/nihui/cain-ncnn-vulkan#video-interpolation-with-ffmpeg You need the FFMPEG executable. 
To get to 24 from 6 images you would need to interpolate three images. I think this implementation interpolates one frame by default. I did not test if the results are good enough to interpolate more frames. If you are looking for a gui tool maybe this is something for you: https://grisk.itch.io/dain-app?download

**Comment by n00mkrad** [comment]
> FFMPEG is just used to extract the frames as described here https://github.com/nihui/cain-ncnn-vulkan#video-interpolation-with-ffmpeg You need the FFMPEG executable.
> To get to 24 from 6 images you would need to interpolate three images. I think this implementation interpolates one frame by default. I did not test if the results are good enough to interpolate more frames. If you are looking for a gui tool maybe this is something for you: https://grisk.itch.io/dain-app?download

What you linked is outdated and isn't based on CAIN.

This is my GUI, which actually includes CAIN:

https://nmkd.itch.io/flowframes

**Comment by natowi** [comment]
@n00mkrad Thanks for the tip. GUI tools are rare and hard to find.

**Comment by herrartist** [comment]
Dear NOOMKRAD,

when using RIFE-interpolation I get his error message:
"Output folder does not contain frames - an error must have occurd during interpolation!"
I tried input of 720p, 1080 HD and Ultra-HD as PNGs and H.264 file.

My PC specs are: Intel Core I9 3,6 GHz,  RAM 32 GB, Windows Pro for Workstations 10/64 bit, 
Graphic card: NVIDIA GeForce GTX1660 Ti Memory 6GB

What can I do to be able to run RIFE-interpolation?

Kind regards

Martin Hans Schmitt, mail@martinhansschmitt.com

**Comment by n00mkrad** [comment]
> Dear NOOMKRAD,
> 
> when using RIFE-interpolation I get his error message:
> "Output folder does not contain frames - an error must have occurd during interpolation!"
> I tried input of 720p, 1080 HD and Ultra-HD as PNGs and H.264 file.
> 
> My PC specs are: Intel Core I9 3,6 GHz, RAM 32 GB, Windows Pro for Workstations 10/64 bit,
> Graphic card: NVIDIA GeForce GTX1660 Ti Memory 6GB
> 
> What can I do to be able to run RIFE-interpolation?
> 
> Kind regards
> 
> Martin Hans Schmitt, [mail@martinhansschmitt.com](mailto:mail@martinhansschmitt.com)

Please contact me on Discord (click the blue Discord button in Flowframes to join). I'm still working out some of the error handling.

**Comment by nihui** [comment]
model path is now properly handled in the latest version
