### ISSUE TITLE
OSX version - zsh: segmentation fault

### ISSUE THREAD

**Issue by Hudaldadi** [nihui/cain-ncnn-vulkan#14]
Beside that the Windows and Ubuntu Version produces black frames.

OSX Version quits with zsh: segmentation fault

After nihui did such a good job in the older versions.

nihui/cain-ncnn-vulkan. seems to be broken : (

**Comment by Hudaldadi** [comment]
on a system with 2 gpu and linux this cain version works.

so I think it is just a problem with GPU IDs

**Comment by brenoprata10** [comment]
Same for me

**Comment by Hudaldadi** [comment]
you need to jump into the same directory when you call it at commend line:

cd {App folder}
