### ISSUE TITLE
output frames of a solid color instead of interpolation

### ISSUE THREAD

**Issue by Katzenwerfer** [nihui/cain-ncnn-vulkan#5]
I have used the command like this `cain-ncnn-vulkan -i input_frames -o output_frames -g 0`
but the only thing that it prints is
```
find_blob_index_by_name x.1 failed
find_blob_index_by_name x.3 failed
find_blob_index_by_name 4070 failed
```
over and over, and in the output frames the "interpolated frames are only solid colors"
idk if i'm missing a step or something

**Comment by Mar2ck** [comment]
you need to move the model files from the cain folder into the same folder as the executable. it's the same issue as this https://github.com/nihui/dain-ncnn-vulkan/issues/2

**Comment by Katzenwerfer** [comment]
well, i moved ` cain.bin ` and ` cain.param ` to the same folder as the .exe, but it's still giving me the same error

**Comment by Mar2ck** [comment]
The current working directory of your terminal needs to be at the same folder as the model files since it just looks for them in "./"

**Comment by Katzenwerfer** [comment]
Ok, now this is working

**Comment by Katzenwerfer** [comment]
Imao this make me do some extra effort, but I guess that's how it is

**Comment by Katzenwerfer** [comment]
thanks
