### ISSUE TITLE
tile-size values over 2048 have no effect

### ISSUE THREAD

**Issue by lextra2** [nihui/cain-ncnn-vulkan#6]
I can get at most around 1200MB of VRAM allocated to the app by using `-t 2048`
Greater values, like 8192 for example have no effect and neither does increasing `load:proc:save`
This is with a 8GB Vram GPU and with using 1920x1080 resolution images.

**Comment by Aeroform-se** [comment]
Now I didn't program this and basically have no clue, however, it sounds to me if you enter a tile of 2048(x2048), that tile would cover the entire full HD frame. In other words, running bigger tiles wouldn't help/increase anything as the full frame is already covered by 1 single tile.

**Comment by lextra2** [comment]
> 
> 
> Now I didn't program this and basically have no clue, however, it sounds to me if you enter a tile of 2048(x2048), that tile would cover the entire full HD frame. In other words, running bigger tiles wouldn't help/increase anything as the full frame is already covered by 1 single tile.

Mhh. Sure it makes sense. But the reason it got me confused was because 
dain-ncnn-vulkan uses much more VRam with a smaller tile-size.

**Comment by Mar2ck** [comment]
Judging by the model files, cain has one but dain has four models so that's probably why it uses so much more vram

**Comment by nihui** [comment]
tile support dropped for faster speed
since https://github.com/nihui/cain-ncnn-vulkan/commit/fb9746a9021e81a6f39c131d7d35f4f95c2e644e
